version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/NineLanCacheUI"
    schedule:
      interval: "daily"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(npm)"
    groups:
      ui-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(github-actions)"
    groups:
      github-actions:
        patterns:
          - "*"
  
  - package-ecosystem: "nuget"
    directory: "/NineLanCacheUI-API"
    schedule:
      interval: "daily"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(nuget)"
    ignore:
      - dependency-name: "*"
        versions: [">=10.0.0"]
    groups:
      api-dependencies:
        patterns:
          - "*"