services:
  api:
    image: ninepiece2/nine-lancache-ui:api
    restart: unless-stopped
    ports:
      - '7401:80'
    environment:
      - LanCacheLogsDirectory=/var/ninelancacheui/lancachelogs
      - LanCacheUIDataDirectory=/var/ninelancacheuidata
      # - ConnectionStrings__DefaultConnection=Data Source={LanCacheUIDataDirectory}/database/nine-lancache-ui.db;
      - TZ=America/Toronto
      - ASPNETCORE_ENVIRONMENT=Development
      - LANG=en_CA.UTF-8
      - DirectSteamIntegration=true
      - SkipLinesBasedOnBytesRead=true
      - ASPNETCORE_HTTP_PORTS=80
    volumes:
      - "/home/romit/lancacheUI/backenData:/var/ninelancacheuidata"
      - "/mnt/NvmeSSD/LanCacheData/logs:/var/ninelancacheui/lancachelogs:ro"
    dns:
      - 192.168.15.200
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  ui:
    image: ninepiece2/nine-lancache-ui:ui
    restart: unless-stopped
    ports:
      - '7402:3000'
    environment:
      - API_BASE_URL=http://192.168.15.200:7401       
      - NGINX_URL=http://nginx:80                 
      - AllowedHosts=*