name: Build API Docker CI

on:
  push:
    branches:
      - main
    paths:
      - NineLanCacheUI-API/**
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v7.0.0

        - name: Login to Docker Hub
          uses: docker/login-action@v4.2.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Login to Github Container Registry
          uses: docker/login-action@v4.2.0
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4
          with:
            driver: docker-container

        - name: Get current time
          id: current_time_step
          run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

        - name: Build and push
          uses: docker/build-push-action@v7.2.0
          with:
            context: ./NineLanCacheUI-API
            file: ./NineLanCacheUI-API/NineLanCacheUI-API/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/nine-lancache-ui:api-beta
              ghcr.io/ninepiece2/ninelancacheui:api-beta
            build-args: |
              VERSION=beta
              BUILD_DATE=${{ steps.current_time_step.outputs.time }}
              VCS_REF=${{ github.sha }}