name: Build UI Docker CI

on:
  push:
    branches:
      - main
    paths:
      - NineLanCacheUI/**
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container
            
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./NineLanCacheUI
            file: ./NineLanCacheUI/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/nine-lancache-ui:ui
            build-args: |
              SYNCFUSION_LICENSE=${{ secrets.SyncfusionLicense }}
        